"""add updated_at in task_table

Revision ID: 9adc912e3c07
Revises: 35c6fde175d2
Create Date: 2025-12-28 13:18:00.786437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adc912e3c07'
down_revision: Union[str, Sequence[str], None] = '35c6fde175d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_table', sa.Column('updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_table', 'updated_at')
    # ### end Alembic commands ###
